spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:jblog
    data: classpath:data-dev.sql

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info
    io.github.cncsl: DEBUG

jblog:
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: 3w09/7F3FKm+A35TkTpBIUxZxyKnL4E025al90arJoJRP6OkoTg6trM+EvGNXav8eELXQ8IjmHdQ6JrX7Th4MQORug5sjwE4PkZyR92aOAUfAgQaiGx2N4QVyBHSbxFy
        # 一天
        token-validity-in-seconds: 86400
        # 七天
        token-validity-in-seconds-for-remember-me: 604800
---
spring:
  devtools:
    add-properties: false
  config:
    activate:
      on-profile: prod


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//localhost:3306/jblog?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: jblog_dba
    password: jblog_dba

  jpa:
    show-sql: false

  redis:
    username: jblog_dba
    password: jblog_dba

logging:
  level:
    root: info

jblog:
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: d92Ga4WQJD0pkqwQlPSqXQYpcyhCq0kH+jhrPa1Na8cU2VPGzIRDz3sL9DZuVxw6LCpRJF17R8+XKe1wvQUoPj9atM4mnzLgm47EURbqSbTob5EvfzstZwhOTNQjQLlj
        # 一天
        token-validity-in-seconds: 86400
        # 七天
        token-validity-in-seconds-for-remember-me: 604800

---