spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:jblog
    data: classpath:data-dev.sql

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: info
    io.github.cncsl: DEBUG

jblog:
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: nOxLSyszPYYmmkHhr4HCDDhMx+bg02iF2dmCKo2cT/kRuxoJiassSu0RMEr2z3sP
        # 一天
        token-validity-in-seconds: 86400
        # 七天
        token-validity-in-seconds-for-remember-me: 604800
---
spring:
  devtools:
    add-properties: false
  config:
    activate:
      on-profile: prod


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jblog?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: Csl130bc24

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    username: jblog_dba
    password: jblog_dba

logging:
  level:
    root: info

jblog:
  security:
    authentication:
      jwt:
        # openssl rand -base64 64
        base64-secret: 0GyNU7XyYZPvQTyQSs4j4KcVKG26obkwsohPE3hxRl2XVGnKsdnvnA2wFuDN9dyv
        # 一天
        token-validity-in-seconds: 86400
        # 七天
        token-validity-in-seconds-for-remember-me: 604800

---